### ISSUE TITLE
能不能渲染海浪?

### ISSUE THREAD

**Issue by AffiNiNy** [hongfaqiu/cesium-wind-layer#3]
如 windy 的海浪 [wave](https://www.windy.com/zh/-%E8%8F%9C%E5%8D%95/menu?waves,-48.203,-32.673,8,m:cnzafYC)
![image](https://github.com/user-attachments/assets/3800701e-0163-4c68-9332-8bd35d770ddb)

如 earth.null 的波浪 [波浪](https://earth.nullschool.net/zh-cn/#current/ocean/primary/waves/orthographic)
![image](https://github.com/user-attachments/assets/68e91504-67bd-4035-b1b7-a90c8f6f52ac)

cesium-wind-layer库功能能不能兼容显示海浪?

**Comment by hongfaqiu** [comment]
调整粒子宽度、长度、速度即可模拟海浪。
友情提醒，目前此库是实验性质的，后面还会多次迭代

**Comment by AffiNiNy** [comment]
@hongfaqiu  Thanks for your advise👍
请问~   大佬对海浪数据解析有没有经验? 

比如说 NOMADS 提供的 GFS Wave 数据, 这些变量完全看不懂, 也没找到解释呢
[GFS Wave](https://nomads.ncep.noaa.gov/gribfilter.php?ds=gfswave)
![image](https://github.com/user-attachments/assets/58cc0cf5-a270-43ef-8e49-030e5ea6341a)

**Comment by mickae1** [comment]
@hongfaqiu great work, do you know how to convert a grib2 file to the json format that will work with your library ?

**Comment by hongfaqiu** [comment]
@mickae1 Thank you for your recognition. This is an experimental warehouse. Currently, the display effect for data in other ranges is not ideal. I am trying to develop a new rendering scheme, which may include referring to the wave effect of Ventusky.
Regarding the grib2 file. Maybe I can create some packages to convert this format.

**Comment by mickae1** [comment]
Can you tell which software did you use to extract the data?
Did you use a command line? 

@hongfaqiu

**Comment by hongfaqiu** [comment]
@mickae1 Yes, I used the [gdal-async](https://github.com/mmomtchev/node-gdal-async) tool on Node.js to convert multi-time period NC data into the current format.

**Comment by mickae1** [comment]
> @mickae1 Yes, I used the [gdal-async](https://github.com/mmomtchev/node-gdal-async) tool on Node.js to convert multi-time period NC data into the current format.

Thx , but do you have an idea how to convert it ? give me some tips ? or share the code ? I don't want the full code, but at least a part of it :)

**Comment by mickae1** [comment]
@hongfaqiu do you have a documentation that explain how to use gdal-async to read a grib2 file ?

**Comment by mickae1** [comment]
@hongfaqiu 

I found this example to read the file, 

and this is what I made to convert the file, but it's not working ^^ 




`
    const gdal = require("gdal-async")
    const util = require('util')
    
    const ds = gdal.open("20241202_232002_GFS_P25_.grb2", "r", "GRIB")
    //const ds = gdal.open("gfswave.t18z.global.0p25.f219.grib2", "r", "GRIB")
    
    // raster dimensions
    const size = ds.rasterSize
    
    // geotransform
    const geotransform = ds.geoTransform
    
    var minU  = 9999
    var maxU = 0
    const arrayU = []
    var minV  = 9999
    var maxV = 0
    const arrayV = []
    
    // bands
    ds.bands.forEach((band) => {
      let metadata = band.getMetadata()
      if(metadata["GRIB_ELEMENT"] == "UGRD" || metadata["GRIB_ELEMENT"] == "VGRD"){
	  	      
	      if(metadata["GRIB_ELEMENT"] == "UGRD"){
		    minU  = 9999
		    maxU = 0
	      }else{
		    minV  = 9999
		    maxV = 0
	      }
	      
	      var i = 0;
	      for( var y= 0; y < size.y; y++ ){
		      for( var x = 0; x < size.x; x++ ){
			    const val = band.pixels.get(x, y)
			    if(metadata["GRIB_ELEMENT"] == "UGRD"){
				    minU = Math.min(minU, val)
				    maxU = Math.max(maxU, val)
				    arrayU[i++] = val
			    }else{
				    minV = Math.min(minV, val)
				    maxV = Math.max(maxV, val)
				    arrayV[i++] = val
			    }
		      }
	      }   
      }
    })
    
    
    const jsonObj = {};
    jsonObj.name = "test";
    jsonObj.width = size.x;
    jsonObj.height = size.y;
    jsonObj.bbox = [ geotransform[0], geotransform[3], geotransform[0] + size.x * geotransform[1] + size.y * geotransform[2], geotransform[3] + size.x * geotransform[4] + size.y * geotransform[5] ];
    jsonObj.u = {};
    jsonObj.u.min = minU;
    jsonObj.u.max = maxU;
    jsonObj.u.array = arrayU;
    jsonObj.v = {};
    jsonObj.v.min = minV;
    jsonObj.v.max = maxV;
    jsonObj.v.array = arrayV;
    
    var fs = require('fs');
    
    fs.writeFile ("wind.json", JSON.stringify(jsonObj), function(err) {
        if (err) throw err;
		    console.log('complete');
        }
    );
`

do you know, what is wrong ?
